version: "3"
services:
  reservierung-app:
    restart: on-failure
    container_name: reservierung
    build: ./
    expose:
      - "10001"
    ports:
      - 10001:9000
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - docker-mysql

  docker-mysql:
    restart: always
    container_name: docker-mysql
    image: mysql
    environment:
      MYSQL_DATABASE: reservierung
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "6666:3306"
    healthcheck:
      test: '/usr/bin/mysql --user=root --password=test1234 --execute "SHOW DATABASES;"'
      interval: 4s
      timeout: 20s
      retries: 1
