version: "3"
services:
  gutschein-app:
    container_name: gutschein-app
    image: kiranowhere/gutscheinservice
    restart: on-failure
    ports:
      - 10555:9090
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - docker-mysql
  produkt-app:
    container_name: produkt-app
    image: kiranowhere/produktservice
    restart: on-failure
    ports:
      - 10666:9000
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - docker-mysql
      - gutschein-app
  docker-mysql:
    container_name: docker-mysql
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: sampledb
      MYSQL_ROOT_PASSWORD: XXXXXXXXXX
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 6666:3306
    healthcheck:
      test: '/usr/bin/mysql --user=root --password=2017_August25 --execute "SHOW DATABASES"'
      interval: 4s
      timeout: 20s
      retries: 5
