apiVersion: v1
kind: Service
metadata:
  name: docker-mysql-service
  labels:
    app: docker-mysql
spec:
  selector:
    app: docker-mysql
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30001
