apiVersion: v1
kind: Service
metadata:
  name: produkt-app-service
  labels:
    app: produkt-app
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30003
  selector:
    app: produkt-app
